name: Build Android APK (Simple)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Create Gradle Wrapper
      run: |
        # 创建gradle wrapper目录
        mkdir -p gradle/wrapper
        
        # 下载gradle 7.6的wrapper jar
        echo "Downloading gradle-wrapper.jar..."
        wget -O gradle/wrapper/gradle-wrapper.jar https://services.gradle.org/distributions/gradle-7.6-wrapper.jar
        
        # 创建gradle-wrapper.properties
        cat > gradle/wrapper/gradle-wrapper.properties << 'EOF'
        distributionBase=GRADLE_USER_HOME
        distributionPath=wrapper/dists
        zipStoreBase=GRADLE_USER_HOME
        zipStorePath=wrapper/dists
        distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-all.zip
        EOF
        
        # 创建gradlew脚本
        cat > gradlew << 'EOF'
        #!/usr/bin/env sh
        APP_HOME="`pwd -P`"
        CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
        exec java -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
        EOF
        
        chmod +x gradlew
        
        echo "=== Gradle wrapper created ==="
        ls -la gradle/wrapper/
        ls -la gradlew

    - name: Build debug APK
      run: |
        ./gradlew clean
        ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: wechat-notification-interceptor-simple
        path: app/build/outputs/apk/debug/app-debug.apk
