name: Build Android APK (Alternative)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Create complete Gradle project structure
      run: |
        echo "Creating Gradle project from scratch..."
        
        # 确保所有必要目录存在
        mkdir -p gradle/wrapper
        mkdir -p app/src/main/java/com/example/wechatnotificationinterceptor
        mkdir -p app/src/main/res/layout
        mkdir -p app/src/main/res/values
        mkdir -p app/src/main/res/drawable
        mkdir -p app/src/main/res/mipmap-hdpi
        
        # 使用gradle init创建基础项目
        gradle init --type basic --dsl groovy --project-name WeChatNotificationInterceptor
        
        # 生成wrapper
        gradle wrapper --gradle-version=7.3.3
        chmod +x gradlew
        
        echo "=== Generated files ==="
        ls -la
        ls -la gradle/wrapper/

    - name: Verify project files
      run: |
        echo "=== Checking essential files ==="
        test -f build.gradle && echo "✅ build.gradle exists" || echo "❌ build.gradle missing"
        test -f app/build.gradle && echo "✅ app/build.gradle exists" || echo "❌ app/build.gradle missing"
        test -f settings.gradle && echo "✅ settings.gradle exists" || echo "❌ settings.gradle missing"
        test -f gradlew && echo "✅ gradlew exists" || echo "❌ gradlew missing"
        test -f gradle/wrapper/gradle-wrapper.jar && echo "✅ gradle-wrapper.jar exists" || echo "❌ gradle-wrapper.jar missing"

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace --debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: wechat-notification-interceptor-debug-alt
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          **/*.log
          **/build/reports/
