name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Debug project structure
      run: |
        echo "=== Current directory ==="
        pwd
        echo "=== Project files ==="
        ls -la
        echo "=== Gradle configuration files ==="
        echo "--- build.gradle ---"
        cat build.gradle
        echo "--- settings.gradle ---"
        cat settings.gradle

    - name: Initialize Gradle Wrapper
      run: |
        # 确保gradle wrapper目录存在
        mkdir -p gradle/wrapper
        
        # 使用gradle 7.6初始化wrapper
        echo "Initializing Gradle wrapper with version 7.6..."
        gradle wrapper --gradle-version=7.6
        
        # 确保gradlew可执行
        chmod +x gradlew
        
        # 验证文件
        echo "=== Gradle wrapper files ==="
        ls -la gradle/wrapper/
        ls -la gradlew*

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build debug APK
      run: |
        echo "Building APK..."
        ./gradlew clean assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: wechat-notification-interceptor-debug
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          **/*.log
          **/build/reports/


