name: Build Android APK (AndroidX Fix)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      env:
        SKIP_JDK_VERSION_CHECK: true

    - name: Force AndroidX Configuration
      run: |
        echo "=== Forcing AndroidX configuration ==="
        
        # 创建干净的gradle.properties
        cat > gradle.properties << 'EOF'
        org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
        org.gradle.parallel=true
        org.gradle.caching=true
        android.useAndroidX=true
        android.enableJetifier=true
        android.nonTransitiveRClass=true
        org.gradle.configuration-cache=false
        EOF
        
        # 验证配置
        echo "=== gradle.properties content ==="
        cat gradle.properties
        
        # 确保没有隐藏字符
        dos2unix gradle.properties 2>/dev/null || true

    - name: Initialize Gradle Wrapper
      run: |
        mkdir -p gradle/wrapper
        gradle wrapper --gradle-version=7.6
        chmod +x gradlew
        
        echo "=== Gradle wrapper initialized ==="
        ls -la gradle/wrapper/
        ls -la gradlew*

    - name: Verify AndroidX Configuration
      run: |
        echo "=== Verifying AndroidX configuration ==="
        ./gradlew properties | grep -i android || true
        
        echo "=== Checking for AndroidX dependencies ==="
        ./gradlew :app:dependencies --configuration debugRuntimeClasspath | grep androidx || true

    - name: Clean and Build
      run: |
        echo "=== Cleaning project ==="
        ./gradlew clean
        
        echo "=== Building debug APK ==="
        ./gradlew assembleDebug --stacktrace --info

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: wechat-notification-interceptor-androidx-fix
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-androidx-fix
        path: |
          **/*.log
          **/build/reports/
